
[versions]
kotlin-version = "2.1.10"
ktor-version = "3.2.0"
logback-version = "1.4.14"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor-version"}
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
